package code

type PaymentCode int

const (
	PendingReview              PaymentCode = -30001 // Операция находится на рассмотрении, идет опрос статуса операции
	LimitBlock                 PaymentCode = -20010 // Блокировка по лимиту
	DSerror                    PaymentCode = -2025  // Ошибки по 3DS
	DSFrictionlessForbidden    PaymentCode = -2024  // Frictionless запрещен
	DSAuthNotPossibleIssuer    PaymentCode = -2023  // 3DS аутентификация невозможна эмитентом
	DSProcessingImpossible     PaymentCode = -2022  // Проведение операции по 3DS невозможно
	InvalidECI                 PaymentCode = -2020  // Неверный ECI
	DSAuthNotPossibleAcquirer  PaymentCode = -2018  // 3DS аутентификация невозможна эквайером
	ClientDidNotReturnFromPage PaymentCode = -2014  // Клиент не вернулся с платежной страницы
	TooManyPaymentAttempts     PaymentCode = -2013  // Превышено количество попыток оплаты
	ClientDidNotReturnFromACS  PaymentCode = -2009  // Клиент не вернулся с ACS
	PaymentTimeout             PaymentCode = -2007  // Срок оплаты истек
	DSecureFailed              PaymentCode = -2006  // 3DS авторизация не пройдена
	InvalidPaymentToken        PaymentCode = -301   // Некорректный платежный токен
	WaitingForPaymentAttempt   PaymentCode = -100   // Ожидание попытки оплаты

	Success                       PaymentCode = 0      // Платёж прошёл успешно
	IdentityVerificationRequired  PaymentCode = 1      // Требуется подтверждение личности
	CardBlockedUnknown            PaymentCode = 4      // Карта заблокирована по неизвестной причине
	CardDeclinedUnknown           PaymentCode = 5      // Карта отклонена по неизвестной причине
	OrderNotFound                 PaymentCode = 6      // Транзакция не найдена
	OperationNotAllowed           PaymentCode = 7      // Операция невозможна в текущем состоянии транзакции
	PermissionDenied              PaymentCode = 8      // Пользователю не доступен запрос
	InsufficientFunds             PaymentCode = 20     // Недостаточно средств
	SecurityCall                  PaymentCode = 37     // Вызов безопасности
	CardBlocked                   PaymentCode = 62     // Карта заблокирована
	SecurityViolation             PaymentCode = 63     // Нарушение безопасности
	CardNotAllowedForTransaction  PaymentCode = 72     // Карта не разрешена для данного типа транзакции
	CardExpiryMismatch            PaymentCode = 73     // Срок действия не совпадает
	InvalidAccount                PaymentCode = 78     // Недействительная учетная запись
	InvalidCVC                    PaymentCode = 82     // Неверный CVC
	PreAuthTimeTooLong            PaymentCode = 87     // Время предавторизации слишком велико
	UnknownResponseStatus         PaymentCode = 90     // Неизвестный статус ответа
	DuplicateTransmission         PaymentCode = 94     // Дублирование передачи
	ExceededCardLimit             PaymentCode = 100    // Превышен лимит карты
	CardExpired                   PaymentCode = 101    // Карта просрочена
	IssuerDeclined                PaymentCode = 103    // Эмитент отклонил платеж
	TooManyPINTries               PaymentCode = 106    // Превышено количество ввода PIN
	InvalidTerminalConfig         PaymentCode = 109    // Неверная конфигурация терминала
	InvalidPaymentAmount          PaymentCode = 110    // Недопустимая сумма платежа
	InvalidCardNumber             PaymentCode = 111    // Неверный номер карты
	InsufficientFundsAlt          PaymentCode = 116    // Недостаточно средств
	InvalidPIN                    PaymentCode = 117    // Неверный PIN
	SecurityViolationAlt          PaymentCode = 119    // Нарушение безопасности
	IssuerOperationNotAllowed     PaymentCode = 120    // Операция не разрешена банком
	TransactionLimitExceeded      PaymentCode = 121    // Превышен лимит транзакции
	TransactionCountLimitExceeded PaymentCode = 123    // Превышено количество транзакций
	TechnicalError                PaymentCode = 124    // Техническая ошибка
	InvalidCardNumberAlt          PaymentCode = 125    // Неверный номер карты
	FraudMonitoringDeclined       PaymentCode = 151    // Отклонено фрод-мониторингом
	ServiceNotAllowed             PaymentCode = 181    // Сервис не разрешен
	CardLost                      PaymentCode = 203    // Карта утеряна
	CardLostAlt                   PaymentCode = 204    // Карта утеряна
	CardLostRestriction           PaymentCode = 208    // Ограничение использования карты
	ParticipantBlocked            PaymentCode = 212    // Участник заблокирован
	RecurringPaymentStopped       PaymentCode = 240    // Рекуррентная транзакция остановлена
	CardInternetBlocked           PaymentCode = 555    // Интернет-транзакции запрещены
	TransactionCycleLimitExceeded PaymentCode = 814    // Превышен предел количества транзакций
	CardReportedStolen            PaymentCode = 823    // Карта украдена
	BalanceOrLimitExceeded        PaymentCode = 902    // Превышен баланс/лимит
	InvalidMessageFormatIssuer    PaymentCode = 904    // Неверный формат сообщения
	CardExpiredAlt                PaymentCode = 906    // Карта просрочена
	IssuerUnavailable             PaymentCode = 907    // Нет связи с эмитентом
	UnknownDecline                PaymentCode = 909    // Отклонено по неизвестной причине
	DeclinedContactShop           PaymentCode = 911    // Операция отклонена, обратитесь в магазин
	BankUnavailable               PaymentCode = 912    // Банк-эмитент недоступен
	InvalidMessageFormatMPS       PaymentCode = 913    // Неверный формат сообщения МПС
	OriginalTransactionNotFound   PaymentCode = 914    // Оригинальная транзакция не найдена
	UnableToProcess               PaymentCode = 916    // Невозможно обработать
	CardRestrictions              PaymentCode = 920    // Ограничения по карте
	InvalidMerchantID             PaymentCode = 941    // Неверный идентификатор продавца
	ReconciliationError           PaymentCode = 950    // Ошибка согласования
	SystemMalfunction             PaymentCode = 959    // Неисправность системы
	OriginalAmountInvalid         PaymentCode = 968    // Оригинальная сумма неверна
	ServiceUnavailable            PaymentCode = 998    // Услуга недоступна
	SuspectedFraud                PaymentCode = 999    // Подозрение на мошенничество
	TooManyRequestsSameCardExpiry PaymentCode = 1112   // Превышено количество запросов по карте (PAN+EXPIRY)
	TooManyRequestsSameCard       PaymentCode = 1113   // Превышено количество запросов по карте (PAN)
	TooManyRequestsLinkedCard     PaymentCode = 1114   // Превышено количество запросов по карте в связке
	TooManyFailedPayments         PaymentCode = 1115   // Превышено количество неуспешных оплат
	TooManyRequestsTerminal       PaymentCode = 1116   // Превышено количество запросов по карте (терминал)
	TooManyRequestsMerchant       PaymentCode = 1117   // Превышено количество запросов по карте (продавец)
	TooManyRequestsSameAmount     PaymentCode = 1118   // Превышено количество запросов (сумма+валюта)
	RefundInProgress              PaymentCode = 1120   // Возврат в процессе
	DSRequired                    PaymentCode = 1434   // Требуется авторизация 3DS
	InvalidOperation              PaymentCode = 2002   // Неверная операция
	DSRequiredForPayment          PaymentCode = 2003   // Платежи без 3DS запрещены
	OrderAlreadyCancelled         PaymentCode = 2012   // Заказ уже отменен
	DSForbidden                   PaymentCode = 2016   // 3DS запрещен
	ProcessingQueueLimitReached   PaymentCode = 2023   // Достигнут лимит потоков
	CardBlockedAlt                PaymentCode = 2030   // Карта заблокирована
	PaymentDeclinedByMerchant     PaymentCode = 4005   // Отклонено продавцом
	IssuerDeclinedAResA           PaymentCode = 4032   // Эмитент отклонил с ARes=A
	DuplicateOrder                PaymentCode = 8204   // Заказ-дубль
	InvalidPaymentData            PaymentCode = 71015  // Некоторые данные платежа недействительны
	ProcessingTimeoutSendFailed   PaymentCode = 151018 // Таймаут в процессинге (отправка не удалась)
	ProcessingTimeoutNoResponse   PaymentCode = 151019 // Таймаут в процессинге (ответ не получен)
)
