package code

const (
	PendingReview              int = -30001 // Операция находится на рассмотрении, идет опрос статуса операции
	LimitBlock                 int = -20010 // Блокировка по лимиту
	DSerror                    int = -2025  // Ошибки по 3DS
	DSFrictionlessForbidden    int = -2024  // Frictionless запрещен
	DSAuthNotPossibleIssuer    int = -2023  // 3DS аутентификация невозможна эмитентом
	DSProcessingImpossible     int = -2022  // Проведение операции по 3DS невозможно
	InvalidECI                 int = -2020  // Неверный ECI
	DSAuthNotPossibleAcquirer  int = -2018  // 3DS аутентификация невозможна эквайером
	ClientDidNotReturnFromPage int = -2014  // Клиент не вернулся с платежной страницы
	TooManyPaymentAttempts     int = -2013  // Превышено количество попыток оплаты
	ClientDidNotReturnFromACS  int = -2009  // Клиент не вернулся с ACS
	PaymentTimeout             int = -2007  // Срок оплаты истек
	DSecureFailed              int = -2006  // 3DS авторизация не пройдена
	InvalidPaymentToken        int = -301   // Некорректный платежный токен
	WaitingForPaymentAttempt   int = -100   // Ожидание попытки оплаты

	Success                       int = 0      // Платёж прошёл успешно
	IdentityVerificationRequired  int = 1      // Требуется подтверждение личности
	CardBlockedUnknown            int = 4      // Карта заблокирована по неизвестной причине
	CardDeclinedUnknown           int = 5      // Карта отклонена по неизвестной причине
	OrderNotFound                 int = 6      // Транзакция не найдена
	OperationNotAllowed           int = 7      // Операция невозможна в текущем состоянии транзакции
	PermissionDenied              int = 8      // Пользователю не доступен запрос
	InsufficientFunds             int = 20     // Недостаточно средств
	SecurityCall                  int = 37     // Вызов безопасности
	CardBlocked                   int = 62     // Карта заблокирована
	SecurityViolation             int = 63     // Нарушение безопасности
	CardNotAllowedForTransaction  int = 72     // Карта не разрешена для данного типа транзакции
	CardExpiryMismatch            int = 73     // Срок действия не совпадает
	InvalidAccount                int = 78     // Недействительная учетная запись
	InvalidCVC                    int = 82     // Неверный CVC
	PreAuthTimeTooLong            int = 87     // Время предавторизации слишком велико
	UnknownResponseStatus         int = 90     // Неизвестный статус ответа
	DuplicateTransmission         int = 94     // Дублирование передачи
	ExceededCardLimit             int = 100    // Превышен лимит карты
	CardExpired                   int = 101    // Карта просрочена
	IssuerDeclined                int = 103    // Эмитент отклонил платеж
	TooManyPINTries               int = 106    // Превышено количество ввода PIN
	InvalidTerminalConfig         int = 109    // Неверная конфигурация терминала
	InvalidPaymentAmount          int = 110    // Недопустимая сумма платежа
	InvalidCardNumber             int = 111    // Неверный номер карты
	InsufficientFundsAlt          int = 116    // Недостаточно средств
	InvalidPIN                    int = 117    // Неверный PIN
	SecurityViolationAlt          int = 119    // Нарушение безопасности
	IssuerOperationNotAllowed     int = 120    // Операция не разрешена банком
	TransactionLimitExceeded      int = 121    // Превышен лимит транзакции
	TransactionCountLimitExceeded int = 123    // Превышено количество транзакций
	TechnicalError                int = 124    // Техническая ошибка
	InvalidCardNumberAlt          int = 125    // Неверный номер карты
	FraudMonitoringDeclined       int = 151    // Отклонено фрод-мониторингом
	ServiceNotAllowed             int = 181    // Сервис не разрешен
	CardLost                      int = 203    // Карта утеряна
	CardLostAlt                   int = 204    // Карта утеряна
	CardLostRestriction           int = 208    // Ограничение использования карты
	ParticipantBlocked            int = 212    // Участник заблокирован
	RecurringPaymentStopped       int = 240    // Рекуррентная транзакция остановлена
	CardInternetBlocked           int = 555    // Интернет-транзакции запрещены
	TransactionCycleLimitExceeded int = 814    // Превышен предел количества транзакций
	CardReportedStolen            int = 823    // Карта украдена
	BalanceOrLimitExceeded        int = 902    // Превышен баланс/лимит
	InvalidMessageFormatIssuer    int = 904    // Неверный формат сообщения
	CardExpiredAlt                int = 906    // Карта просрочена
	IssuerUnavailable             int = 907    // Нет связи с эмитентом
	UnknownDecline                int = 909    // Отклонено по неизвестной причине
	DeclinedContactShop           int = 911    // Операция отклонена, обратитесь в магазин
	BankUnavailable               int = 912    // Банк-эмитент недоступен
	InvalidMessageFormatMPS       int = 913    // Неверный формат сообщения МПС
	OriginalTransactionNotFound   int = 914    // Оригинальная транзакция не найдена
	UnableToProcess               int = 916    // Невозможно обработать
	CardRestrictions              int = 920    // Ограничения по карте
	InvalidMerchantID             int = 941    // Неверный идентификатор продавца
	ReconciliationError           int = 950    // Ошибка согласования
	SystemMalfunction             int = 959    // Неисправность системы
	OriginalAmountInvalid         int = 968    // Оригинальная сумма неверна
	ServiceUnavailable            int = 998    // Услуга недоступна
	SuspectedFraud                int = 999    // Подозрение на мошенничество
	TooManyRequestsSameCardExpiry int = 1112   // Превышено количество запросов по карте (PAN+EXPIRY)
	TooManyRequestsSameCard       int = 1113   // Превышено количество запросов по карте (PAN)
	TooManyRequestsLinkedCard     int = 1114   // Превышено количество запросов по карте в связке
	TooManyFailedPayments         int = 1115   // Превышено количество неуспешных оплат
	TooManyRequestsTerminal       int = 1116   // Превышено количество запросов по карте (терминал)
	TooManyRequestsMerchant       int = 1117   // Превышено количество запросов по карте (продавец)
	TooManyRequestsSameAmount     int = 1118   // Превышено количество запросов (сумма+валюта)
	RefundInProgress              int = 1120   // Возврат в процессе
	DSRequired                    int = 1434   // Требуется авторизация 3DS
	InvalidOperation              int = 2002   // Неверная операция
	DSRequiredForPayment          int = 2003   // Платежи без 3DS запрещены
	OrderAlreadyCancelled         int = 2012   // Заказ уже отменен
	DSForbidden                   int = 2016   // 3DS запрещен
	ProcessingQueueLimitReached   int = 2023   // Достигнут лимит потоков
	CardBlockedAlt                int = 2030   // Карта заблокирована
	PaymentDeclinedByMerchant     int = 4005   // Отклонено продавцом
	IssuerDeclinedAResA           int = 4032   // Эмитент отклонил с ARes=A
	DuplicateOrder                int = 8204   // Заказ-дубль
	InvalidPaymentData            int = 71015  // Некоторые данные платежа недействительны
	ProcessingTimeoutSendFailed   int = 151018 // Таймаут в процессинге (отправка не удалась)
	ProcessingTimeoutNoResponse   int = 151019 // Таймаут в процессинге (ответ не получен)
)
